# Generic event-flow validation for every active icepack dataset
#
# (c) 2026 Mikael Mieskolainen
# Licensed under the MIT License <http://opensource.org/licenses/MIT>.

import subprocess
from pathlib import Path

import numpy as np
import pyjson5 as json5
import pytest
from core.io import readers, steering
from core.io.steering import load_dataset
from core.stats.validation import check_physics, comparison_samples
from pyHepMC3 import HepMC3 as hepmc

from tests.technical.support.iceplot import assert_iceplot_report
from tests.technical.support.output import INTEGRATED_CROSS_SECTION_COLUMNS, PhysicsOutput, write_literature_table

ROOT = Path(__file__).resolve().parents[3]
ICEPACK_ROOT = ROOT / "icepack"


# Compute every active non-helper icepack dataset in stable order
def icepack_datasets():
    datasets = []
    for path in sorted(ICEPACK_ROOT.rglob("dataset.json")):
        relative = path.relative_to(ICEPACK_ROOT)
        if any(part.startswith("_") or "._old" in part for part in relative.parts):
            continue
        with path.open(encoding="utf-8") as stream:
            dataset = json5.load(stream)
        if dataset.get("active", False):
            datasets.append(path)
    return tuple(datasets)


DATASETS = icepack_datasets()
INTEGRATED_DATASETS = tuple(
    path
    for path in DATASETS
    if json5.loads(path.read_text(encoding="utf-8")).get("type") in {"INTEGRATED_LITERATURE", "INTEGRATED_HEPDATA"}
)
UNIT_LABELS = {3: "mb", 6: "ub", 9: "nb", 12: "pb", 15: "fb"}


# Cache reports generated by the generic and aggregate tests in one pytest session
@pytest.fixture(scope="session")
def icepack_report_cache():
    return {}


# Check four-momentum conservation including undecayed outgoing systems
def assert_event_kinematics(report):
    paths = {path for _, _, _, sample in comparison_samples(report) for path in sample.get("input_files", [])}
    assert paths, "iceplot report contains no event input files"
    for path in sorted(paths):
        assert Path(path).is_file(), path
        reader = hepmc.ReaderAscii(path)
        checked = 0
        try:
            for _ in range(100):
                event = hepmc.GenEvent()
                reader.read_event(event)
                if reader.failed():
                    break
                beams = list(event.beams())
                final = [p for p in event.particles() if not p.end_vertex()]
                assert beams and final, (path, event.event_number())
                initial_momenta = np.asarray([[p.momentum().e(), p.momentum().px(), p.momentum().py(), p.momentum().pz()]
                                              for p in beams], dtype=np.longdouble)
                final_momenta = np.asarray([[p.momentum().e(), p.momentum().px(), p.momentum().py(), p.momentum().pz()]
                                            for p in final], dtype=np.longdouble)
                assert np.isfinite(initial_momenta).all() and np.isfinite(final_momenta).all(), path
                assert len(event.weights()) > 0 and np.isfinite(event.weights()).all(), path
                scale = np.abs(initial_momenta).sum() + np.abs(final_momenta).sum()
                tolerance = 4096.0 * np.finfo(float).eps * scale
                if event.attribute_as_string("graniitti_converter_mode") in {"isolated-shower", "full-shower"}:
                    shower_tolerance = float(event.attribute_as_string("graniitti_closure_tolerance"))
                    recorded = float(event.attribute_as_string("graniitti_closure_max_abs"))
                    assert np.isfinite(shower_tolerance) and shower_tolerance > 0.0, path
                    assert np.isfinite(recorded) and 0.0 <= recorded <= shower_tolerance, path
                    assert event.attribute_as_string("graniitti_closure_pass") == "1", path
                    unit = 1000.0 if event.momentum_unit() == hepmc.Units.MEV else 1.0
                    tolerance = max(tolerance, unit * shower_tolerance)
                residual = initial_momenta.sum(axis=0) - final_momenta.sum(axis=0)
                assert np.max(np.abs(residual)) <= tolerance, (path, event.event_number(), residual, tolerance)
                energy2 = final_momenta[:, 0] ** 2
                momentum2 = (final_momenta[:, 1:] ** 2).sum(axis=1)
                shell_tolerance = 4096.0 * np.finfo(float).eps * (energy2 + momentum2)
                assert (final_momenta[:, 0] > 0.0).all(), (path, event.event_number())
                assert (energy2 - momentum2 >= -shell_tolerance).all(), (path, event.event_number())
                checked += 1
        finally:
            reader.close()
        assert checked > 0, path


# Execute one icepack and return its validated machine-readable iceplot output
def run_icepack(dataset_path, request, test_output_dir, report_cache):
    if dataset_path in report_cache:
        return report_cache[dataset_path]
    dataset, _ = load_dataset(str(dataset_path), cdir=ROOT)
    validation = dataset.get("validation", {})
    requested_loopscreen = request.config.getoption("--LOOPSCREEN")
    required_loopscreen = validation.get("loopscreen")
    loopscreen = int(required_loopscreen) if required_loopscreen is not None else requested_loopscreen

    relative = dataset_path.parent.relative_to(ICEPACK_ROOT)
    output_root = test_output_dir / "icepack"
    command = [
        "bash",
        "icepack/run.sh",
        "--WEIGHTED",
        str(int(request.config.getoption("--WEIGHTED"))),
        "--output-dir",
        str(output_root),
    ]
    if loopscreen is not None:
        command.extend(("--LOOPSCREEN", str(int(loopscreen))))
    event_override = request.config.getoption("--NEVENTS")
    required_events = validation.get("nevents")
    nevents = event_override if event_override is not None else required_events
    if nevents is not None:
        command.extend(("--NEVENTS", str(nevents)))
    command.append(str(relative))

    result = subprocess.run(
        command,
        cwd=ROOT,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    print(result.stdout)
    assert result.returncode == 0, result.stdout

    tag = "__".join(relative.parts)
    report_path = output_root / tag / "reports" / f"{tag}.json"
    report = assert_iceplot_report(report_path)
    assert Path(report["hepdata"]).resolve() == dataset_path.resolve()
    check_physics(report)
    assert_event_kinematics(report)
    report_cache[dataset_path] = report
    return report


# Execute one icepack and validate only its machine-readable iceplot output
@pytest.mark.parametrize(
    "dataset_path",
    DATASETS,
    ids=[str(path.parent.relative_to(ICEPACK_ROOT)) for path in DATASETS],
)
def test_icepack_event_flow(
    dataset_path,
    request,
    test_output_dir,
    icepack_report_cache,
):
    run_icepack(dataset_path, request, test_output_dir, icepack_report_cache)


# Compute the cross section report sample for one literature set
def integrated_report_sample(report, set_index):
    observables = report["sets"][set_index]["observables"]
    matches = [item for item in observables if item["observable"] == "cross_section"]
    assert len(matches) == 1
    samples = matches[0]["samples"]
    assert len(samples) == 1
    return samples[0]


# Build one integrated comparison row through the same reader used by iceplot
def integrated_table_row(dataset, report, set_index, dataset_path):
    entry = dataset["sets"][set_index]
    histogram = next(item for item in entry["hist"] if item["obs"] == "cross_section")
    obs, _ = steering.load_observables(entry["obs"], dataset_path=dataset_path, cdir=ROOT)
    data, _ = readers.read_hepdata(entry, dataset["datapath"], dataset["type"], obs,
                reader=dataset["reader"], dataset_path=dataset_path, cdir=str(ROOT))
    measurement = data["cross_section"]
    unit = histogram.get("unit", measurement.get("unit"))
    exponent = next(power for power, label in UNIT_LABELS.items() if label == unit)
    scale = 10.0 ** (12 - exponent)
    conversion = histogram["scale"] * 10.0**exponent
    sample = integrated_report_sample(report, set_index)
    value = float(measurement["y"][0]) * conversion
    assert sample["data_integral"] == pytest.approx(value * scale)
    errors = {name: {side: float(np.sqrt(sum(float(item[side][0])**2 for item in sources))) * conversion
                    for side in ("down", "up")} if sources else None
              for name, sources in {
                  "stat": [item for item in measurement["uncertainties"] if item["category"] == "statistical"],
                  "syst": [item for item in measurement["uncertainties"] if item["category"] != "statistical"
                           and item["name"] not in {"lumi", "luminosity"}],
                  "lumi": [item for item in measurement["uncertainties"] if item["name"] in {"lumi", "luminosity"}],
              }.items()}
    return {
        "state": measurement.get("channel") or entry["name"],
        "phase_space": measurement.get("cuts") or entry.get("title", entry.get("cuts", "")),
        "source": measurement["source"],
        "cross_section": value,
        "unit": unit,
        "statistical_error": errors["stat"],
        "systematic_error": errors["syst"],
        "luminosity_error": errors["lumi"],
        "integration_error": sample["integral_error"] / scale,
        "ratio_to_data": sample["integral"] / sample["data_integral"],
    }


# Run every integrated publication comparison and print its text and LaTeX tables
def test_integrated_xs_table(
    request,
    test_output_dir,
    icepack_report_cache,
):
    rows = []
    for dataset_path in INTEGRATED_DATASETS:
        dataset = json5.loads(dataset_path.read_text(encoding="utf-8"))
        report = run_icepack(
            dataset_path,
            request,
            test_output_dir,
            icepack_report_cache,
        )
        rows.extend(
            integrated_table_row(dataset, report, set_index, str(dataset_path))
            for set_index in range(len(dataset["sets"]))
        )

    output = PhysicsOutput("integrated_cross_sections")
    _, text_path, latex_path = write_literature_table(
        output,
        "integrated_cross_sections",
        columns=INTEGRATED_CROSS_SECTION_COLUMNS,
        rows=rows,
        metadata={
            "references": sorted({str(Path(dataset["datapath"]) / histogram["file"])
                    for path in INTEGRATED_DATASETS
                    for dataset in [json5.loads(path.read_text(encoding="utf-8"))]
                    for entry in dataset["sets"] for histogram in entry["hist"]}),
            "icepacks": [
                str(path.parent.relative_to(ICEPACK_ROOT)) for path in INTEGRATED_DATASETS
            ],
        },
    )
    print(f"\nIntegrated literature table: {text_path}\n")
    print(text_path.read_text(encoding="utf-8"))
    print(f"Integrated literature LaTeX table: {latex_path}\n")
    print(latex_path.read_text(encoding="utf-8"))
    assert rows
