# Test MadGraph support generation
#
# (c) 2026 Mikael Mieskolainen
# Licensed under the MIT License <http://opensource.org/licenses/MIT>.

import errno
import importlib
import json
import os
import re
import shutil
import stat
import sys
from pathlib import Path

import pytest


# Load one MG2GRA module from the repository without relying on the working directory
def load_module(name):
    root = Path(__file__).resolve().parents[3]
    module_dir = root / "develop/MG2GRA"
    qualified = name if name == "regenerate" else f"modules.{name}"
    sys.path.insert(0, str(module_dir))
    try:
        module = importlib.import_module(qualified)
    finally:
        sys.path.remove(str(module_dir))
    return module


# Preserve spinor normalization when the longitudinal sum cancels
@pytest.mark.parametrize("momentum", ["pp", "p[0]"])
@pytest.mark.parametrize("maximum", ["max", "std::max"])
@pytest.mark.parametrize("zero", ["0.0", "0.00"])
def test_helas_conversion_rationalizes_spinors(momentum, maximum, zero):
    converter = load_module("mg5_support")
    source = f"pp3 = {maximum}({momentum} + p[3], {zero});"
    result = converter.transform_helas_source(source, "HelAmps_sm.h", "Runtime/Models/sm")
    assert result == (
        "pp3 = (p[3] < 0.0 ? (p[1] * p[1] + p[2] * p[2]) / "
        f"({momentum} - p[3]) : {momentum} + p[3]);"
    )
    assert converter.transform_helas_source(result, "HelAmps_sm.h", "Runtime/Models/sm") == result


# Require the real MadGraph installation for generation API checks
@pytest.fixture
def mg5_root():
    executable = os.environ.get("MG5AMC") or shutil.which("mg5_aMC")
    if executable is None:
        pytest.skip("MadGraph generation requires MG5AMC or mg5_aMC on PATH")
    return load_module("regenerate").resolve_mg5(executable).parent.parent


# Check colorless photon fusion through the real MadGraph API in an isolated directory
def test_family_color_api_isolated_work_dir(tmp_path, mg5_root):
    family = load_module("mg5_family")
    original = Path.cwd()
    work_dir = tmp_path / "mg5_api"
    result = family.generate_family_color_structure(mg5_root, work_dir, "sm", [], ["a a > e+ e-"])
    assert result
    channels = [channel for process in result for channel in process.canonical]
    assert len(channels) == 1
    assert channels[0].signature == (22, 22, -11, 11)
    assert channels[0].representations == (1, 1, 1, 1)
    assert channels[0].flows == (((0, 0),) * 4,)
    assert Path.cwd() == original


# Compute the incoming and stable-final projection of exact generated channels
def channel_pairs(channels):
    return tuple((channel.initial, channel.final) for channel in channels)


# Compute one checked in family and its selected model manifest
def checked_in_family_manifest(regenerate, family_name):
    root = Path(__file__).resolve().parents[3]
    manifest = regenerate.load_manifest(root / "develop/MG2GRA/processes.json")
    family = next(entry for entry in manifest["families"] if entry["name"] == family_name)
    return family, manifest["models"][family["model"]]


# Compute one checked in generated family header or source path
def checked_in_family_path(root, layout, family, filename, *, source=False):
    directory = layout.family_cpp_directory(family["projection"], family["name"])
    relative = (
        layout.cpp_source_path(directory, filename)
        if source
        else layout.header_path(directory, filename)
    )
    return root / relative


# Verify model suffixes are discovered instead of assuming the Standard Model
def test_non_sm_model_support_names_discovered():
    support = load_module("mg5_support")
    files = support.discover_process_model(
        '#include "Parameters_my_ufo.h"\n',
        '#include "HelAmps_my_ufo.h"\n',
    )
    assert files.parameter_class == "Parameters_my_ufo"
    assert files.parameter_header == "Parameters_my_ufo.h"
    assert files.helas_header == "HelAmps_my_ufo.h"
    assert files.model_suffix == "my_ufo"


# Verify all generated text is canonicalized without trailing whitespace
def test_generated_text_whitespace_canonical():
    converter = load_module("standalone")
    normalized = converter.normalize_whitespace("first  \r\nsecond\t\r\n\r\n")

    assert normalized == "first\nsecond\n"


# Verify structural transforms reject unvalidated MadGraph releases
def test_version_requires_exact_supported_version(tmp_path):
    regenerate = load_module("regenerate")
    source = tmp_path / "CPPProcess.cc"
    source.write_text(
        "// Generated by MadGraph5_aMC@NLO v. 2.9.28, 2026-01-01\n",
        encoding="utf-8",
    )

    with pytest.raises(RuntimeError, match="Unsupported MadGraph version 2.9.28"):
        regenerate.validate_generator_stamp(source)


# Verify generated parameter state is value-owned and only used alpha couplings are adapted
def test_param_thread_local_dependencies():
    support = load_module("mg5_support")
    layout = load_module("output_layout")
    raw_header = """
class Parameters_my_ufo {
 public:
  static Parameters_my_ufo * getInstance();
  void setDependentParameters();
  void setDependentCouplings();
 private:
  static Parameters_my_ufo * instance;
};
"""
    raw_source = """
#include "Parameters_my_ufo.h"
#include <iostream>
Parameters_my_ufo * Parameters_my_ufo::instance = 0;
Parameters_my_ufo * Parameters_my_ufo::getInstance()
{
  if (instance == 0) instance = new Parameters_my_ufo();
  return instance;
}
void Parameters_my_ufo::setIndependentCouplings()
{
  GC_A = -(mdl_q * mdl_complexi);
  GC_B = mdl_g * mdl_complexi;
}
void Parameters_my_ufo::setDependentParameters()
{
  mdl_G = 2 * sqrt(aS * M_PI);
}
void Parameters_my_ufo::setDependentCouplings()
{
  GC_B = mdl_G * mdl_complexi;
}
"""
    header = support.transform_parameters_header(raw_header, "Parameters_my_ufo", alpha_zero=True)
    source = support.transform_parameters_source(
        raw_source,
        "Parameters_my_ufo",
        "Parameters_my_ufo.h",
        "mdl_q",
        None,
        137.03599908,
        layout.model_cpp_directory("my_ufo"),
    )

    assert "getInstance" not in header
    assert "instance" not in header
    assert "setDependentParameters(double alpS)" in header
    assert "setAlphaQEDZero" in header
    assert "getInstance" not in source
    assert "aS = alpS;" in source
    alpha_block = source[source.index("void Parameters_my_ufo::setAlphaQEDZero") :]
    alpha_block = alpha_block[: alpha_block.index("}", 1)]
    assert "GC_A =" in alpha_block
    assert "GC_B =" not in alpha_block


# Verify generic integration keeps MadGraph HELAS numerical branches unchanged
def test_helas_transform_generated_function_bodies():
    support = load_module("mg5_support")
    layout = load_module("output_layout")
    raw = """#include "HelAmps_my_ufo.h"
#include <cstdlib>
using namespace std;
void HELAS::generated(double vmass, double pp, double p[4],
                      complex<double> M3, int nhel) {
  static complex<double> cI = complex<double>(0., 1.);
  if (vmass != 0.0) { pp = vmass; }
  if (pp == 0.0) { p[0] = pp; }
  if (p[1] == 0.0) { p[2] = p[1]; }
  if (M3 != 0.) { M3 = cI; }
  if (nhel == 0) { nhel = 1; }
  cerr << "Invalid helicity in txxxxx.";
  exit(1);
}
"""
    directory = layout.model_cpp_directory("my_ufo")
    converted = support.transform_helas_source(raw, "HelAmps_my_ufo.h", directory)
    expected = support.narrow_std_namespace(
        raw.replace(
            '#include "HelAmps_my_ufo.h"',
            f'#include "{layout.include_path(directory, "HelAmps_my_ufo.h")}"',
        )
    )

    assert converted == expected
    assert "if (vmass != 0.0)" in converted
    assert "if (pp == 0.0)" in converted
    assert "if (p[1] == 0.0)" in converted
    assert "if (M3 != 0.)" in converted
    assert "if (nhel == 0)" in converted
    assert "static std::complex<double> cI" in converted
    assert 'std::cerr << "Invalid helicity in txxxxx.";' in converted
    assert "exit(1);" in converted
    assert "fpclassify" not in converted
    assert "throw" not in converted


# Verify aggregate support validation catches missing HELAS and model parameters
def test_aggregate_dependency_validation_strict():
    support = load_module("mg5_support")
    process = "MG5_my_ufo::FFV1_0(p, w); pars.GC_A;"
    support.validate_dependency_union(
        [process],
        "void FFV1_0();",
        "class Parameters_my_ufo { double GC_A; };",
        "my_ufo",
    )
    with pytest.raises(RuntimeError, match="HELAS=.*FFV1_0"):
        support.validate_dependency_union(
            [process],
            "void UNUSED();",
            "class Parameters_my_ufo { double GC_A; };",
            "my_ufo",
        )
    with pytest.raises(RuntimeError, match="parameters=.*GC_A"):
        support.validate_dependency_union(
            [process],
            "void FFV1_0();",
            "class Parameters_my_ufo {};",
            "my_ufo",
        )


# Verify the installed SLHA parser is reproducible from converted MG5 support
def test_slha_support_is_reproducible():
    support = load_module("mg5_support")
    layout = load_module("output_layout")
    root = Path(__file__).resolve().parents[3]
    raw_header = "class SLHABlock {};\nclass SLHAReader {};\n"
    raw_source = "void SLHABlock::set_entry() {}\nvoid SLHAReader::read_slha_file() {}\n"

    header = support.transform_slha_header(raw_header)
    source = support.transform_slha_source(raw_source)
    assert header == (root / layout.header_path(layout.RUNTIME, "read_slha.h")).read_text()
    assert source == (root / layout.cpp_source_path(layout.RUNTIME, "read_slha.cc")).read_text()


# Install one minimal standalone tree for converter provenance tests
def write_installed_support_tree(regenerate, root):
    layout = load_module("output_layout")
    process_include = root / layout.header_path(layout.DURHAM, "AMP_MG5_test.h")
    process_source = root / layout.cpp_source_path(layout.DURHAM, "AMP_MG5_test.cc")
    model_directory = layout.model_cpp_directory("sm")
    model_include = root / layout.header_path(model_directory, "HelAmps_sm.h")
    model_source = root / layout.cpp_source_path(model_directory, "HelAmps_sm.cc")
    process_include.parent.mkdir(parents=True)
    process_source.parent.mkdir(parents=True)
    model_include.parent.mkdir(parents=True)
    model_source.parent.mkdir(parents=True)
    process_include.write_text(
        f'#include "{layout.include_path(model_directory, "Parameters_sm.h")}"\n'
    )
    process_source.write_text(
        f'#include "{layout.include_path(model_directory, "HelAmps_sm.h")}"\n'
    )
    for path, content in (
        (model_include, "void helas();\n"),
        (model_source, "void helas() {}\n"),
        (
            root / layout.header_path(model_directory, "Parameters_sm.h"),
            "class Parameters_sm {};\n",
        ),
        (
            root / layout.cpp_source_path(model_directory, "Parameters_sm.cc"),
            "Parameters_sm parameters;\n",
        ),
    ):
        path.write_text(content)
    header = regenerate.transform_slha_header("class SLHABlock {};\nclass SLHAReader {};\n")
    source = regenerate.transform_slha_source(
        "void SLHABlock::set_entry() {}\nvoid SLHAReader::read_slha_file() {}\n"
    )
    runtime_header = root / layout.header_path(layout.RUNTIME, "read_slha.h")
    runtime_source = root / layout.cpp_source_path(layout.RUNTIME, "read_slha.cc")
    runtime_header.parent.mkdir(parents=True, exist_ok=True)
    runtime_source.parent.mkdir(parents=True, exist_ok=True)
    runtime_header.write_text(header)
    runtime_source.write_text(source)
    color = root / layout.source_path(layout.color_path(layout.DURHAM_PROJECTION, "test"))
    color.parent.mkdir(parents=True)
    color.write_text('{"projector": "exact"}\n')


# Verify validate-only provenance detects support tampering and converter changes
def test_converter_input_fingerprint(tmp_path, monkeypatch):
    regenerate = load_module("regenerate")
    layout = load_module("output_layout")
    write_installed_support_tree(regenerate, tmp_path)
    manifest = {
        "models": {"sm": {"import": "sm"}},
        "processes": [
            {
                "name": "test",
                "model": "sm",
                "process": "g g > g g",
                "projection": "durham",
            }
        ],
        "families": [],
    }
    state_path = tmp_path / layout.source_path(layout.converter_path())
    monkeypatch.setattr(regenerate, "ROOT", tmp_path)
    monkeypatch.setattr(regenerate, "CONVERTER_STATE_PATH", state_path)
    monkeypatch.setattr(regenerate, "photon_registry_paths", lambda _manifest, _root: [])
    regenerate.install_converter_state(manifest)
    regenerate.validate_converter_state(manifest)

    helas_source = tmp_path / layout.cpp_source_path(
        layout.model_cpp_directory("sm"), "HelAmps_sm.cc"
    )
    helas_source.write_text("tampered\n")
    with pytest.raises(RuntimeError, match="managed support"):
        regenerate.validate_converter_state(manifest)
    helas_source.write_text("void helas() {}\n")

    changed = json.loads(json.dumps(manifest))
    changed["models"]["sm"]["alpha_qed"] = {
        "charge": "mdl_ee",
        "charge_square": "mdl_ee__exp__2",
    }
    with pytest.raises(RuntimeError, match="managed support"):
        regenerate.validate_converter_state(changed)

    monkeypatch.setattr(regenerate, "converter_source_digest", lambda: "0" * 64)
    with pytest.raises(RuntimeError, match="managed support"):
        regenerate.validate_converter_state(manifest)


# Verify converter provenance covers runtime selection and family channel sidecars
def test_converter_state_covers_runtime_sidecars(tmp_path, monkeypatch):
    regenerate = load_module("regenerate")
    layout = load_module("output_layout")
    write_installed_support_tree(regenerate, tmp_path)
    durham = tmp_path / layout.source_path(layout.color_path("durham", "test"))
    channels = tmp_path / layout.source_path(layout.channels_path("parton", "MG5_TEST"))
    channels.parent.mkdir(parents=True)
    channels.write_text('{"family": "MG5_TEST"}\n')
    manifest = {
        "models": {"sm": {"import": "sm"}},
        "processes": [
            {
                "name": "test",
                "model": "sm",
                "process": "g g > g g",
                "projection": "durham",
            }
        ],
        "families": [{"name": "MG5_TEST", "projection": "parton"}],
    }
    state_path = tmp_path / layout.source_path(layout.converter_path())
    monkeypatch.setattr(regenerate, "ROOT", tmp_path)
    monkeypatch.setattr(regenerate, "CONVERTER_STATE_PATH", state_path)
    monkeypatch.setattr(regenerate, "photon_registry_paths", lambda _manifest, _root: [])

    regenerate.install_converter_state(manifest)
    state = json.loads(state_path.read_text())
    assert set(state["sidecars"]) == {
        layout.source_path(layout.color_path("durham", "test")),
        layout.source_path(layout.channels_path("parton", "MG5_TEST")),
    }
    regenerate.validate_converter_state(manifest)

    durham.write_text('{"projector": "tampered"}\n')
    with pytest.raises(RuntimeError, match="managed support"):
        regenerate.validate_converter_state(manifest)


# Keep fixed topology and projector validation outside generated helicity loops
def test_standalone_process_init():
    standalone = load_module("standalone")
    regenerate = load_module("regenerate")
    layout = load_module("output_layout")
    root = Path(__file__).resolve().parents[3]
    manifest = regenerate.load_manifest(root / "develop/MG2GRA/processes.json")
    helicities = "const int helicities[ncomb][nexternal] = {{1, 1, 1, 1}};"
    projected = standalone.make_calc_color_projected_helicity("AMP", 1, helicities, 22)
    prepared = standalone.make_calc_color_projected_prepared("AMP", helicities)
    flow = standalone.make_calc_color_flow_helicity("AMP", 1, helicities, 1, 22)
    for emitted in (projected, prepared, flow):
        assert "validate_decay_topology" not in emitted
        assert "AllFinite" not in emitted
        assert "calculate_wavefunctions" in emitted
        assert "calculate_color_flows" in emitted
    assert "KinematicsFailure" in projected
    assert "setup_kinematics(lts)" in projected
    assert "gra::BilinearProduct(projector_view, jamp_view)" in projected
    for entry in manifest["processes"]:
        directory = layout.projection_cpp_directory(entry["projection"])
        converted = (root / layout.cpp_source_path(directory, f"AMP_MG5_{entry['name']}.cc")).read_text()
        assert "validate_decay_topology" not in converted
        assert "MatchProcess(lts.decaytree)" not in converted


# Verify one registry command generates every standalone and aggregate export
def test_registry_covers_standalone_process(tmp_path):
    regenerate = load_module("regenerate")
    root = Path(__file__).resolve().parents[3]
    manifest = regenerate.load_manifest(root / "develop/MG2GRA/processes.json")
    commands, process_exports, support_exports, family_exports = regenerate.build_mg5_commands(
        manifest, tmp_path
    )

    assert "gg_yy" not in process_exports
    assert set(process_exports) == {entry["name"] for entry in manifest["processes"]}
    assert set(support_exports) == {"sm"}
    assert set(family_exports) == {
        "MG5_PP_Z",
        "MG5_PP_ZJ",
        "MG5_PP_JJ",
        "MG5_PP_W",
        "MG5_YY_JJ",
        "MG5_YY_WW",
        "MG5_YY_ZJJ",
    }
    assert commands.count("output standalone_cpp") == 24
    assert "generate g g > a a QCD=2 QED=2 [noborn=QCD]" not in commands
    assert commands.count("set complex_mass_scheme True --allow_qed") == 1
    assert commands.index("set complex_mass_scheme True --allow_qed") < commands.index(
        "generate a a > w+ w-"
    )
    assert "define p = g u d s c b u~ d~ s~ c~ b~" in commands
    assert commands.count("add process a a > z") == 14
    for entry in manifest["processes"]:
        assert process_exports[entry["name"]].is_relative_to(tmp_path)


# Verify a model with only one family still receives an MG5 export command
def test_registry_generates_family_only_model(tmp_path):
    regenerate = load_module("regenerate")
    manifest = {
        "models": {"bsm": {"import": "my_bsm", "complex_mass_scheme": True}},
        "processes": [],
        "families": [
            {
                "name": "MG5_BSM_PAIR",
                "model": "bsm",
                "definitions": ["define bx = x x~"],
                "processes": ["g g > x x~"],
                "projection": "parton",
                "channel": "pair",
            }
        ],
    }
    commands, process_exports, support_exports, family_exports = regenerate.build_mg5_commands(
        manifest, tmp_path
    )
    assert process_exports == {}
    assert support_exports == {}
    assert set(family_exports) == {"MG5_BSM_PAIR"}
    assert "import model my_bsm" in commands
    assert "set complex_mass_scheme True --allow_qed" in commands
    assert "define bx = x x~" in commands
    assert "generate g g > x x~" in commands
    assert commands.count("output standalone_cpp") == 1


# Write the model and SLHA headers needed by support preflight tests
def write_support_export(path, suffix="sm"):
    source_dir = path / "src"
    source_dir.mkdir(parents=True)
    (source_dir / f"Parameters_{suffix}.h").write_text("class Parameters_test {};\n")
    (source_dir / f"HelAmps_{suffix}.h").write_text("void test();\n")
    (source_dir / "read_slha.h").write_text("class SLHABlock {};\nclass SLHAReader {};\n")
    (source_dir / "read_slha.cc").write_text(
        "void SLHABlock::set_entry() {}\nvoid SLHAReader::read_slha_file() {}\n"
    )


# Verify duplicate global C++ support names stop before any installation
def test_model_suffix_collision(tmp_path):
    regenerate = load_module("regenerate")
    first = tmp_path / "first"
    second = tmp_path / "second"
    write_support_export(first)
    write_support_export(second)

    with pytest.raises(RuntimeError, match="both generate global support suffix sm"):
        regenerate.validate_support_owners({"sm": first, "sm_cms": second})


# Verify a family-only model supplies the common SLHA implementation
def test_family_only_export_supplies_slha_reader(tmp_path, monkeypatch):
    regenerate = load_module("regenerate")
    layout = load_module("output_layout")
    export = tmp_path / "family"
    write_support_export(export, "bsm")
    selected = regenerate.validate_slha_exports({}, {"MG5_BSM": export})
    assert selected == export

    installed = tmp_path / "installed"
    monkeypatch.setattr(regenerate, "ROOT", installed)
    regenerate.install_slha_reader(selected)
    assert (installed / layout.header_path(layout.RUNTIME, "read_slha.h")).is_file()
    assert (installed / layout.cpp_source_path(layout.RUNTIME, "read_slha.cc")).is_file()


# Reject unsupported generated readers through the real conversion before installation
def test_unsupported_slha_exports_fail_preflight(tmp_path):
    regenerate = load_module("regenerate")
    first = tmp_path / "first"
    second = tmp_path / "second"
    write_support_export(first, "sm")
    write_support_export(second, "sm")
    header = second / "src/read_slha.h"
    header.write_text("class UnsupportedReader {};\n")

    with pytest.raises(RuntimeError, match="unsupported structure"):
        regenerate.validate_slha_exports({"first": first}, {"second": second})


# Verify last-model cleanup retires only support without an active owner
def test_orphan_active_model_suffix(tmp_path, monkeypatch):
    regenerate = load_module("regenerate")
    layout = load_module("output_layout")
    for model, suffix in (("old_model", "old"), ("active_model", "active")):
        directory = layout.model_cpp_directory(model)
        for filename, content in (
            (f"HelAmps_{suffix}.h", "header\n"),
            (f"Parameters_{suffix}.h", "header\n"),
        ):
            path = tmp_path / layout.header_path(directory, filename)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        for filename in (f"HelAmps_{suffix}.cc", f"Parameters_{suffix}.cc"):
            path = tmp_path / layout.cpp_source_path(directory, filename)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text("source\n")
    export = tmp_path / "export"
    write_support_export(export, "active")
    monkeypatch.setattr(regenerate, "ROOT", tmp_path)
    transaction = regenerate.InstallTransaction(tmp_path / "journal")

    regenerate.retire_orphaned_model_support({"active_model": export}, transaction)

    old_directory = layout.model_cpp_directory("old_model")
    active_directory = layout.model_cpp_directory("active_model")
    assert not (tmp_path / layout.header_path(old_directory, "HelAmps_old.h")).exists()
    assert not (tmp_path / layout.cpp_source_path(old_directory, "Parameters_old.cc")).exists()
    assert (tmp_path / layout.header_path(active_directory, "HelAmps_active.h")).is_file()
    assert (tmp_path / layout.cpp_source_path(active_directory, "Parameters_active.cc")).is_file()


# Verify declarative masses are replaced structurally without comment assumptions
def test_slha_mass_overrides_are_structural():
    regenerate = load_module("regenerate")
    card = """Block mass
    5 4.700000D+00
   15 1.777000e+00 # MTA
Block yukawa
    5 4.700000e+00 # ymb
"""

    transformed = regenerate.set_slha_masses(card, {"5": 0.0, "15": 1.2345678901234567})
    assert "5 0.0000000000000000e+00" in transformed
    assert "15 1.2345678901234567e+00 # MTA" in transformed
    assert "5 4.700000e+00 # ymb" in transformed
    assert regenerate.slha_masses(transformed, {5, 15}) == {
        5: 0.0,
        15: 1.2345678901234567,
    }


# Verify regeneration updates configured masses while preserving unrelated card values
def test_family_owned_mass_updates(tmp_path):
    regenerate = load_module("regenerate")
    source = tmp_path / "source.dat"
    destination = tmp_path / "destination.dat"
    source.write_text("Block mass\n    5 4.700000e+00 # MB\n")
    destination.write_text(
        "Block mass\n    5 4.800000e+00 # user MB\nBlock custom\n    1 9.900000e+00 # user value\n"
    )
    family = {
        "name": "MG5_TEST",
        "projection": "parton",
        "mass_overrides": {"5": 0.0},
    }

    assert regenerate.install_family_card(source, destination, family)
    assert "5 0.0000000000000000e+00 # user MB" in destination.read_text()
    assert "1 9.900000e+00 # user value" in destination.read_text()


# Verify removed mass ownership restores fresh MG5 values without replacing user fields
def test_family_card_restores_removed_owned_masses(tmp_path):
    regenerate = load_module("regenerate")
    layout = load_module("output_layout")
    source = tmp_path / "source.dat"
    destination = tmp_path / "destination.dat"
    source.write_text(
        "Block mass\n"
        "    5 4.700000e+00 # fresh MB\n"
        "   15 1.777000e+00 # fresh MTA\n"
        "   25 1.250000e+02 # fresh MH\n"
    )
    destination.write_text(
        "Block mass\n"
        "    5 0.000000e+00 # user MB comment\n"
        "   15 0.000000e+00 # user MTA comment\n"
        "   25 1.260000e+02 # user MH\n"
        "Block custom\n"
        "    1 9.900000e+00 # user value\n"
    )
    family = {"name": "MG5_TEST", "projection": "parton", "mass_overrides": {"5": 0.25}}
    sidecar = tmp_path / layout.source_path(layout.channels_path("parton", "MG5_TEST"))
    sidecar.parent.mkdir(parents=True)
    sidecar.write_text(
        json.dumps(
            {
                "family": "MG5_TEST",
                "generation_setup": {"mass_overrides": {"5": 0.0, "15": 0.0}},
            }
        )
    )
    previous = regenerate.installed_family_mass_overrides(family, tmp_path)

    assert regenerate.install_family_card(source, destination, family, previous_overrides=previous)
    content = destination.read_text()
    assert "5 2.5000000000000000e-01 # user MB comment" in content
    assert regenerate.slha_masses(content, {15}) == {15: 1.777}
    assert "# user MTA comment" in content
    assert "25 1.260000e+02 # user MH" in content
    assert "1 9.900000e+00 # user value" in content


# Verify pre-schema sidecars without mass ownership remain compatible
def test_missing_mass_ownership(tmp_path):
    regenerate = load_module("regenerate")
    layout = load_module("output_layout")
    family = {"name": "MG5_TEST", "projection": "parton"}
    sidecar = tmp_path / layout.source_path(layout.channels_path("parton", "MG5_TEST"))
    sidecar.parent.mkdir(parents=True)
    sidecar.write_text(json.dumps({"family": "MG5_TEST", "generation_setup": {"model": "sm"}}))

    assert regenerate.installed_family_mass_overrides(family, tmp_path) == {}


# Compute one complete valid manifest for strict schema mutations
def valid_manifest_data():
    return {
        "models": {
            "sm": {
                "import": "sm",
                "complex_mass_scheme": False,
                "particle_pdgs": {"x": 9000001},
                "alpha_qed": {
                    "charge": "mdl_ee",
                    "charge_square": "mdl_ee__exp__2",
                    "inverse_alpha_zero": 137.0,
                },
            }
        },
        "processes": [
            {
                "name": "test",
                "model": "sm",
                "process": "g g > g g",
                "projection": "durham",
            }
        ],
        "families": [
            {
                "name": "MG5_TEST",
                "model": "sm",
                "definitions": ["define p = g u u~"],
                "processes": ["p p > g g"],
                "process_names": ["test"],
                "projection": "parton",
                "channel": "test",
                "mass_overrides": {"5": 0.0},
            }
        ],
    }


# Replace one nested manifest value by its object and list path
def replace_manifest_value(manifest, path, value):
    if not path:
        return value
    target = manifest
    for component in path[:-1]:
        target = target[component]
    target[path[-1]] = value
    return manifest


# Verify malformed JSON types and unsafe generator fields fail at manifest loading
@pytest.mark.parametrize(
    ("path", "value", "message"),
    (
        ((), [], "MG5 registry must be an object"),
        (("models",), [], "models must be an object"),
        (("models", "sm"), [], "Model sm must be an object"),
        (("models", "sm", "import"), False, "import must be a nonempty"),
        (
            ("models", "sm", "complex_mass_scheme"),
            "true",
            "non-boolean complex_mass_scheme",
        ),
        (("models", "sm", "particle_pdgs"), [], "particle_pdgs must be an object"),
        (("models", "sm", "particle_pdgs", "x"), True, "invalid particle_pdgs"),
        (("models", "sm", "alpha_qed"), [], "alpha_qed must be an object"),
        (
            ("models", "sm", "alpha_qed", "inverse_alpha_zero"),
            True,
            "invalid inverse_alpha_zero",
        ),
        (("processes",), "test", "processes must be a list"),
        (("processes", 0), "test", "Standalone process must be an object"),
        (("processes", 0, "name"), "../test", "safe nonempty identifier"),
        (("processes", 0, "process"), 7, "process must be a nonempty"),
        (("processes", 0, "process"), "g g g g", "invalid MG5 process syntax"),
        (("processes", 0, "projection"), True, "projection must be a nonempty"),
        (("processes", 0, "projection"), "parton", "invalid standalone projection"),
        (("processes", 0, "process"), "a a > g g", "requires incoming g g"),
        (("families",), "MG5_TEST", "families must be a list"),
        (("families", 0), "MG5_TEST", "Generated family must be an object"),
        (("families", 0, "name"), "MG5-TEST", "safe nonempty identifier"),
        (("families", 0, "name"), "DURHAM", "reserved standalone process family"),
        (("families", 0, "name"), "CUSTOM", "must use the MG5_ namespace"),
        (("families", 0, "definitions"), "define p = g", "definitions must be a list"),
        (("families", 0, "definitions"), [7], "entry 0 must be a nonempty"),
        (("families", 0, "definitions"), ["p = g"], "invalid MG5 definitions"),
        (("families", 0, "processes"), "p p > g g", "processes must be a nonempty list"),
        (("families", 0, "processes"), [], "processes must be a nonempty list"),
        (("families", 0, "processes"), [False], "entry 0 must be a nonempty"),
        (("families", 0, "process_names"), [], "process_names must be a nonempty list"),
        (("families", 0, "process_names"), ["one", "two"], "must match processes"),
        (("families", 0, "process_names"), ["bad-name"], "safe nonempty identifier"),
        (("families", 0, "projection"), True, "projection must be a nonempty"),
        (("families", 0, "projection"), "durham", "invalid family projection"),
        (("families", 0, "channel"), "../test", "safe nonempty identifier"),
        (("families", 0, "mass_overrides"), {"b": 0.0}, "invalid PDG id"),
        (("families", 0, "mass_overrides"), {"5": True}, "invalid mass"),
    ),
)
def test_registry_malformed_manifest_fields(tmp_path, path, value, message):
    regenerate = load_module("regenerate")
    manifest = replace_manifest_value(valid_manifest_data(), path, value)
    manifest_path = tmp_path / "processes.json"
    manifest_path.write_text(json.dumps(manifest))

    with pytest.raises(RuntimeError, match=message):
        regenerate.load_manifest(manifest_path)


# Verify unknown manifest fields fail where they are introduced
@pytest.mark.parametrize(
    "path",
    (
        (),
        ("models", "sm"),
        ("models", "sm", "alpha_qed"),
        ("processes", 0),
        ("families", 0),
    ),
)
def test_registry_unknown_manifest_fields(tmp_path, path):
    regenerate = load_module("regenerate")
    manifest = valid_manifest_data()
    target = manifest
    for component in path:
        target = target[component]
    target["typo_field"] = True
    manifest_path = tmp_path / "processes.json"
    manifest_path.write_text(json.dumps(manifest))

    with pytest.raises(RuntimeError, match="unknown fields.*typo_field"):
        regenerate.load_manifest(manifest_path)


# Verify fixed helper names and public family channels have disjoint ownership
@pytest.mark.parametrize(
    ("mutation", "name"),
    (
        ("process", "DurhamRegistry"),
        ("process", "family_channels"),
        ("family_wrapper", "MG5_test"),
    ),
)
def test_output_name_collision(mutation, name):
    regenerate = load_module("regenerate")
    manifest = valid_manifest_data()
    if mutation == "process":
        manifest["processes"][0]["name"] = name
    else:
        duplicate = json.loads(json.dumps(manifest["families"][0]))
        duplicate["name"] = name
        duplicate["channel"] = "other"
        manifest["families"].append(duplicate)

    with pytest.raises(RuntimeError, match="reserved|duplicate amplitude"):
        regenerate.validate_manifest(manifest)


# Verify removed family implementation fields have no compatibility path
@pytest.mark.parametrize("field", ("subprocess_sum", "amplitude", "amplitude_type", "card_alias"))
def test_removed_family_fields(tmp_path, field):
    regenerate = load_module("regenerate")
    manifest = valid_manifest_data()
    manifest["families"][0][field] = True
    manifest_path = tmp_path / "processes.json"
    manifest_path.write_text(json.dumps(manifest))

    with pytest.raises(RuntimeError, match=f"unknown fields.*{field}"):
        regenerate.load_manifest(manifest_path)


# Verify the public wrapper name is derived from one valid family name
def test_registry_derives_family_amp_name():
    registry = load_module("process_registry")
    assert registry.family_wrapper_name(valid_manifest_data()["families"][0]) == "AMP_MG5_test"


# Verify repository validation checks one advertised amplitude
def test_family_amplitude_validation(tmp_path):
    regenerate = load_module("regenerate")
    parton_registry = load_module("parton_registry")
    layout = load_module("output_layout")
    family = {
        "name": "MG5_TEST",
        "projection": "parton",
        "channel": "test",
    }
    with pytest.raises(RuntimeError, match="is not installed"):
        regenerate.validate_family_amplitude(family, tmp_path)

    header = tmp_path / layout.header_path(layout.PARTON, "AMP_MG5_test.h")
    source = tmp_path / layout.cpp_source_path(layout.PARTON, "AMP_MG5_test.cc")
    header.parent.mkdir(parents=True)
    source.parent.mkdir(parents=True)
    header.write_text("class AMP_MG5_test {};\n")
    source.write_text("// MG5_TEST::BuildSubprocesses(channels, card);\n")
    with pytest.raises(RuntimeError, match="header is stale"):
        regenerate.validate_family_amplitude(family, tmp_path)

    header.write_text(parton_registry.amplitude_header(family))
    with pytest.raises(RuntimeError, match="source is stale"):
        regenerate.validate_family_amplitude(family, tmp_path)

    source.write_text(parton_registry.amplitude_source(family))
    regenerate.validate_family_amplitude(family, tmp_path)


# Verify family-only command options cannot silently affect standalone entries
@pytest.mark.parametrize(
    "arguments",
    (
        ["--channel", "test"],
        ["--complex-mass-scheme"],
        ["--mass-override", "5=0"],
        [
            "--add",
            "test",
            "--process",
            "g g > g g",
            "--projection",
            "durham",
            "--channel",
            "test",
        ],
    ),
)
def test_family_only_cli_options_require_add_family(monkeypatch, arguments):
    regenerate = load_module("regenerate")
    monkeypatch.setattr(sys, "argv", ["regenerate.py", *arguments])
    args = regenerate.parse_args()
    manifest = {"models": {"sm": {"import": "sm"}}, "processes": [], "families": []}
    with pytest.raises(RuntimeError, match="require --add-family"):
        regenerate.add_registry_entry(args, manifest)


# Verify invalid CLI additions leave both memory and manifest bytes untouched
def test_invalid_cli_addition_transactional(tmp_path, monkeypatch):
    regenerate = load_module("regenerate")
    manifest = valid_manifest_data()
    original_manifest = json.loads(json.dumps(manifest))
    manifest_path = tmp_path / "processes.json"
    original_bytes = regenerate.dump_manifest(manifest).encode()
    manifest_path.write_bytes(original_bytes)
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "regenerate.py",
            "--manifest",
            str(manifest_path),
            "--add",
            "invalid_gluon",
            "--process",
            "g g > g g",
            "--projection",
            "parton",
        ],
    )
    args = regenerate.parse_args()

    with pytest.raises(RuntimeError, match="requires --projection durham or photon"):
        regenerate.add_registry_entry(args, manifest)

    assert manifest == original_manifest
    assert manifest_path.read_bytes() == original_bytes
    assert not list(tmp_path.glob("processes.json._old*"))


# Verify valid CLI additions stay in memory until regeneration commits
def test_valid_cli_addition_defers_manifest_commit(tmp_path, monkeypatch):
    regenerate = load_module("regenerate")
    manifest = valid_manifest_data()
    original_manifest = json.loads(json.dumps(manifest))
    manifest_path = tmp_path / "processes.json"
    original_bytes = regenerate.dump_manifest(manifest).encode()
    manifest_path.write_bytes(original_bytes)
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "regenerate.py",
            "--manifest",
            str(manifest_path),
            "--add",
            "yy_muons",
            "--process",
            "a a > mu+ mu- QCD=0",
            "--projection",
            "photon",
        ],
    )
    args = regenerate.parse_args()

    candidate = regenerate.add_registry_entry(args, manifest)

    assert manifest == original_manifest
    assert candidate["processes"][-1]["name"] == "yy_muons"
    assert regenerate.load_manifest(manifest_path) == original_manifest
    assert manifest_path.read_bytes() == original_bytes
    assert not list(tmp_path.glob("processes.json._old*"))


# Verify failed generated installations restore all prior destinations
def test_install_restores_replaced_new_files(tmp_path):
    regenerate = load_module("regenerate")
    replaced = tmp_path / "replaced.txt"
    created = tmp_path / "created.txt"
    replaced.write_text("old\n")
    transaction = regenerate.InstallTransaction(tmp_path / "journal")

    regenerate.install_text(replaced, "new\n", transaction)
    regenerate.install_text(created, "created\n", transaction)
    transaction.rollback()

    assert replaced.read_text() == "old\n"
    assert not created.exists()
    assert not list(tmp_path.glob("*._old*"))
    assert not list(tmp_path.glob("*._failed*"))


# Verify a successful transaction retains replaced and retired bytes beside their paths
def test_install_commit_old_outputs_cleans_journal(tmp_path):
    regenerate = load_module("regenerate")
    replaced = tmp_path / "replaced.txt"
    retired = tmp_path / "retired.txt"
    created = tmp_path / "created.txt"
    journal_root = tmp_path / "journal"
    replaced.write_text("old replacement\n")
    retired.write_text("old retired\n")
    (tmp_path / "replaced.txt._old").write_text("prior backup\n")
    transaction = regenerate.InstallTransaction(journal_root)

    regenerate.install_text(replaced, "new replacement\n", transaction)
    regenerate.install_text(created, "new file\n", transaction)
    regenerate.retire_output(retired, transaction)
    transaction.commit()

    assert replaced.read_text() == "new replacement\n"
    assert created.read_text() == "new file\n"
    assert not retired.exists()
    assert (tmp_path / "replaced.txt._old").read_text() == "prior backup\n"
    assert (tmp_path / "replaced.txt._old.1").read_text() == "old replacement\n"
    assert (tmp_path / "retired.txt._old").read_text() == "old retired\n"
    assert not list(journal_root.iterdir())


# Verify rollback restores all prior outputs after a partly completed commit
def test_install_rolls_back_partial_commit(tmp_path, monkeypatch):
    regenerate = load_module("regenerate")
    first = tmp_path / "first.txt"
    second = tmp_path / "second.txt"
    first.write_text("old first\n")
    second.write_text("old second\n")
    journal_root = tmp_path / "journal"
    transaction = regenerate.InstallTransaction(journal_root)
    regenerate.install_text(first, "new first\n", transaction)
    regenerate.install_text(second, "new second\n", transaction)
    move_file = regenerate.move_file
    commits = 0

    def fail_second_commit(source, destination):
        nonlocal commits
        if destination.name.endswith("._old"):
            commits += 1
            if commits == 2:
                raise OSError("injected commit failure")
        move_file(source, destination)

    monkeypatch.setattr(regenerate, "move_file", fail_second_commit)
    with pytest.raises(OSError, match="injected commit failure"):
        transaction.commit()
    transaction.rollback()

    assert first.read_text() == "old first\n"
    assert second.read_text() == "old second\n"
    assert not list(tmp_path.glob("*.txt._old*"))
    failed = {path.read_text() for path in journal_root.rglob("failed_*")}
    assert failed == {"new first\n", "new second\n"}


# Verify generated replacements retain the checked in destination file mode
def test_atomic_install_destination_mode(tmp_path):
    regenerate = load_module("regenerate")
    destination = tmp_path / "generated.cc"
    destination.write_text("old\n")
    destination.chmod(0o754)

    assert regenerate.install_text(destination, "new\n")
    assert destination.read_text() == "new\n"
    assert stat.S_IMODE(destination.stat().st_mode) == 0o754


# Verify transaction backup and rollback fall back safely across filesystems
def test_install_handles_cross_filesystem_moves(tmp_path, monkeypatch):
    regenerate = load_module("regenerate")
    destination = tmp_path / "generated.cc"
    destination.write_text("old\n")
    destination.chmod(0o744)
    transaction = regenerate.InstallTransaction(tmp_path / "journal")

    def cross_filesystem(_source, _destination):
        raise OSError(errno.EXDEV, "cross-device link")

    monkeypatch.setattr(Path, "replace", cross_filesystem)
    regenerate.install_text(destination, "new\n", transaction)
    assert destination.read_text() == "new\n"
    assert stat.S_IMODE(destination.stat().st_mode) == 0o744

    transaction.rollback()
    assert destination.read_text() == "old\n"
    assert stat.S_IMODE(destination.stat().st_mode) == 0o744


# Verify each active standalone keeps only its projection-owned card directory
@pytest.mark.parametrize(
    ("projection", "expected"),
    [
        ("durham", "Durham"),
        ("photon", "Photon"),
    ],
)
def test_orphan_standalone_sidecars(
    tmp_path, monkeypatch, projection, expected
):
    regenerate = load_module("regenerate")
    layout = load_module("output_layout")
    cards = tmp_path / layout.CARDS_ROOT
    for directory in (layout.DURHAM, layout.PHOTON):
        owner = cards / directory / "test"
        owner.mkdir(parents=True)
        (owner / layout.COLOR_DATA).write_text("{}\n")
        (owner / layout.PARAMETER_CARD).write_text("card\n")
    monkeypatch.setattr(regenerate, "ROOT", tmp_path)
    monkeypatch.setattr(regenerate, "CARDS_ROOT", cards)
    manifest = {
        "models": {"sm": {"import": "sm"}},
        "processes": [
            {
                "name": "test",
                "model": "sm",
                "process": "g g > g g" if projection == "durham" else "a a > e+ e-",
                "projection": projection,
            }
        ],
        "families": [],
    }
    transaction = regenerate.InstallTransaction(tmp_path / "journal")

    regenerate.retire_orphaned_outputs(manifest, transaction)
    transaction.commit()

    assert (cards / expected / "test" / layout.COLOR_DATA).is_file()
    retired_directory = layout.PHOTON if expected == layout.DURHAM else layout.DURHAM
    retired = {path.name for path in (cards / retired_directory / "test").glob("*._old")}
    assert retired == {f"{layout.COLOR_DATA}._old", f"{layout.PARAMETER_CARD}._old"}


# Verify managed-output validation rejects arbitrary active standalone JSON sidecars
def test_extra_standalone_sidecars(tmp_path, monkeypatch):
    regenerate = load_module("regenerate")
    layout = load_module("output_layout")
    for root_name in (layout.CPP_INCLUDE_ROOT, layout.CPP_SOURCE_ROOT):
        for directory in (layout.RUNTIME, layout.DURHAM, layout.PHOTON, layout.PARTON):
            (tmp_path / root_name / directory).mkdir(parents=True)
    include_dir = tmp_path / layout.CPP_INCLUDE_ROOT / layout.DURHAM
    source_dir = tmp_path / layout.CPP_SOURCE_ROOT / layout.DURHAM
    cards = tmp_path / layout.CARDS_ROOT
    for directory in (layout.DURHAM, layout.PHOTON, layout.PARTON):
        (cards / directory).mkdir(parents=True)
    process_dir = cards / layout.cards_directory("durham", "test")
    process_dir.mkdir(parents=True)
    marker = "// MadGraph to GRANIITTI conversion done\n"
    (include_dir / "AMP_MG5_test.h").write_text(marker)
    (source_dir / "AMP_MG5_test.cc").write_text(marker)
    (process_dir / layout.PARAMETER_CARD).write_text("card\n")
    (process_dir / layout.COLOR_DATA).write_text("{}\n")
    extra = process_dir / "extra.json"
    extra.write_text("{}\n")
    monkeypatch.setattr(regenerate, "ROOT", tmp_path)
    monkeypatch.setattr(regenerate, "CARDS_ROOT", cards)
    manifest = {
        "models": {"sm": {"import": "sm"}},
        "processes": [{"name": "test", "projection": "durham"}],
        "families": [],
    }

    with pytest.raises(RuntimeError, match="standalone MG5 card data"):
        regenerate.validate_managed_outputs(manifest)
    extra.rename(process_dir / "extra.json._old")
    regenerate.validate_managed_outputs(manifest)

    # Retire one removed family and validate repeatedly after transaction commit
    family_dirs = [tmp_path / root / layout.PHOTON / "MG5_REMOVED"
                   for root in (layout.CPP_INCLUDE_ROOT, layout.CPP_SOURCE_ROOT)]
    for directory in family_dirs:
        directory.mkdir()
        (directory / "saved.txt").write_text("retained source\n")
    transaction = regenerate.InstallTransaction(tmp_path / "journal")
    regenerate.retire_orphaned_outputs(manifest, transaction)
    transaction.commit()
    regenerate.validate_managed_outputs(manifest)
    transaction = regenerate.InstallTransaction(tmp_path / "journal")
    regenerate.retire_orphaned_outputs(manifest, transaction)
    transaction.commit()
    regenerate.validate_managed_outputs(manifest)
    for directory in family_dirs:
        saved = directory.with_name(directory.name + "._old")
        assert (saved / "saved.txt").read_text() == "retained source\n"
        assert list(directory.parent.glob("MG5_REMOVED*")) == [saved]



# Verify changing a family amplitude retires the exact old wrapper pair
def test_orphan_cleanup_exact_family_wrapper_stems(tmp_path, monkeypatch):
    regenerate = load_module("regenerate")
    layout = load_module("output_layout")
    include_dir = tmp_path / layout.CPP_INCLUDE_ROOT / layout.PARTON
    source_dir = tmp_path / layout.CPP_SOURCE_ROOT / layout.PARTON
    include_dir.mkdir(parents=True)
    source_dir.mkdir(parents=True)
    (tmp_path / layout.CARDS_ROOT).mkdir(exist_ok=True)
    for family_name in ("MG5_ACTIVE", "MG5_OLD"):
        stem = f"AMP_MG5_{family_name.removeprefix('MG5_').lower()}"
        (include_dir / f"{stem}.h").write_text(
            f'#include "Graniitti/Amplitude/MG5/Parton/{family_name}/ProcessBase.h"\n'
        )
        (source_dir / f"{stem}.cc").write_text(
            f'#include "Graniitti/Amplitude/MG5/Parton/{family_name}/Processes.h"\n'
        )
    monkeypatch.setattr(regenerate, "ROOT", tmp_path)
    monkeypatch.setattr(regenerate, "CARDS_ROOT", tmp_path / layout.CARDS_ROOT)
    manifest = {
        "models": {"sm": {"import": "sm"}},
        "processes": [],
        "families": [{"name": "MG5_ACTIVE", "projection": "parton"}],
    }
    transaction = regenerate.InstallTransaction(tmp_path / "journal")

    with pytest.raises(RuntimeError, match="Orphaned or missing"):
        regenerate.validate_family_wrappers(manifest, include_dir, source_dir)
    regenerate.retire_orphaned_outputs(manifest, transaction)

    assert (include_dir / "AMP_MG5_active.h").is_file()
    assert (source_dir / "AMP_MG5_active.cc").is_file()
    assert not (include_dir / "AMP_MG5_old.h").exists()
    assert not (source_dir / "AMP_MG5_old.cc").exists()
    regenerate.validate_family_wrappers(manifest, include_dir, source_dir)


# Verify regeneration preserves an existing process parameter card
def test_install_missing_cards(tmp_path):
    regenerate = load_module("regenerate")
    generated = tmp_path / "generated.dat"
    existing = tmp_path / "existing.dat"
    missing = tmp_path / "missing.dat"
    generated.write_text("generated\n")
    existing.write_text("process-specific\n")

    assert not regenerate.install_default_card(generated, existing)
    assert existing.read_text() == "process-specific\n"
    assert regenerate.install_default_card(generated, missing)
    assert missing.read_text() == "generated\n"


# Verify parameter card ownership is canonical and projection local
def test_param_cards_projection_owned_paths():
    layout = load_module("output_layout")
    assert layout.parameter_card_path("durham", "test") == "Durham/test/param_card.dat"
    assert layout.parameter_card_path("parton", "MG5_TEST") == "Parton/MG5_TEST/param_card.dat"


# Verify public channels cannot be shared within one physical projection
def test_duplicate_channel_ownership():
    regenerate = load_module("regenerate")
    manifest = valid_manifest_data()
    duplicate = json.loads(json.dumps(manifest["families"][0]))
    duplicate["name"] = "MG5_OTHER"
    manifest["families"].append(duplicate)

    with pytest.raises(RuntimeError, match="duplicate public family channels"):
        regenerate.validate_manifest(manifest)


# Verify family channel_data covers mirrored beams and complete ordered stable leaves
def test_family_channels_include_generated_mirrors():
    family = load_module("mg5_family")
    raw_source = """
// Process: g d > z d QCD<=1 QED<=1 @1
// *   Decay: z > mu+ mu- WEIGHTED<=2
// Mirror initial state momenta for mirror process
"""
    channels = family.channels(raw_source)
    assert channel_pairs(channels) == (
        ((21, 1), (-13, 13, 1)),
        ((1, 21), (-13, 13, 1)),
    )


# Check MadGraph quark-gluon color flow under beam exchange
@pytest.mark.parametrize("process", ["g u > g u", "u g > g u"])
def test_family_color_structure_exact_mg_order(tmp_path, mg5_root, process):
    family = load_module("mg5_family")
    generated = family.generate_family_color_structure(mg5_root, tmp_path / "mg5_api", "sm", [], [process])
    channels = [channel for subprocess in generated for channel in subprocess.canonical]
    assert len(channels) == 1
    channel = channels[0]
    incoming = (21, 2) if process.startswith("g") else (2, 21)
    assert channel.signature == (*incoming, 21, 2)
    assert channel.representations == tuple(8 if pdg == 21 else 3 for pdg in channel.signature)
    assert channel.flows
    # Cross incoming color lines before checking conservation of every color index
    for flow in channel.flows:
        crossed = [pair[::-1] if index < 2 else pair for index, pair in enumerate(flow)]
        colors = sorted(color for color, _ in crossed if color)
        anticolors = sorted(color for _, color in crossed if color)
        assert colors == anticolors
        for representation, (color, anticolor) in zip(channel.representations, flow, strict=True):
            assert bool(color)
            assert bool(anticolor) is (representation == 8)


# Verify complete exact channels and persistent sidecars preserve color rows losslessly
def test_family_channels_sidecar_roundtrip():
    family = load_module("mg5_family")
    canonical = family.ExternalColorStructure(
        (21, 2, 21, 2),
        (8, 3, 8, 3),
        (((1, 2), (2, 0), (1, 3), (3, 0)),),
    )
    mirrored = family.ExternalColorStructure(
        (2, 21, 21, 2),
        (3, 8, 8, 3),
        (((2, 0), (1, 2), (1, 3), (3, 0)),),
    )
    color = family.SubprocessColorStructure("P1_Sigma_sm_gu_gu", (canonical,), (mirrored,))
    raw_source = """
// Process: g u > g u QCD=2 @1
// Mirror initial state momenta for mirror process
double CPPProcess::matrix_gu_gu()
{
  const int ncolor = 1;
  const double denom[ncolor] = {1};
  const double cf[ncolor][ncolor] = {{1}};
  // Calculate color flows
  jamp[0] = amp[0];
  // Sum and square the color flows
}
"""
    channels = family.complete_channels(raw_source, color)
    family.validate_channels([channels])
    subprocess = family.FamilySubprocess("MG5_TEST_P1", "", "", channels)
    generation_setup = family.family_generation_setup_from_data(
        {
            "model": "sm",
            "model_import": "sm",
            "complex_mass_scheme": False,
            "definitions": [],
            "processes": ["g u > g u QCD=2"],
            "particle_pdgs": {},
            "alpha_qed": None,
            "mass_overrides": {},
        }
    )
    mg5_source = family.mg5_source_from_data({"mg5_version": "2.9.27", "source_digest": "0" * 64})
    channel_data = family.make_family_channels(
        "MG5_TEST", generation_setup, mg5_source, [("P1_Sigma_sm_gu_gu", subprocess)]
    )
    data = family.family_channels_data(channel_data)

    assert family.family_channels_from_data(data) == channel_data
    formatted = family.format_channel(channels[0])
    assert "{8, 3, 8, 3}" in formatted
    assert "ColorFlowLeg{1, 2}" in formatted


# Verify MG5 sigmaHat flavour multiplicities equal exact channel counts
def test_family_channel_multiplicity():
    family = load_module("mg5_family")
    source = """
double CPPProcess::sigmaHat()
{
  if (id1 == 21 && id2 == 2) { return matrix_element[0] * 2; }
  else if (id1 == 2 && id2 == 21) { return matrix_element[1]; }
  return 0.;
}
"""
    channels = (
        family.Channel((21, 2), (21, 2), ()),
        family.Channel((21, 2), (2, 21), ()),
        family.Channel((2, 21), (21, 2), ()),
    )

    assert family.selected_process_multiplicities(source, "CPPProcess") == {
        (21, 2): 2,
        (2, 21): 1,
    }
    family.validate_selected_multiplicities(source, "CPPProcess", channels)
    with pytest.raises(RuntimeError, match="multiplicities and exact channels disagree"):
        family.validate_selected_multiplicities(source, "CPPProcess", channels[:-1])


# Verify direct electroweak final states retain all generated stable leaves
def test_family_stable_leaves():
    family = load_module("mg5_family")
    raw_source = """
// Process: u u~ > mu+ mu- QCD=0 QED<=2 @1
// Mirror initial state momenta for mirror process
"""
    channels = family.channels(raw_source)
    assert channel_pairs(channels) == (
        ((2, -2), (-13, 13)),
        ((-2, 2), (-13, 13)),
    )


# Verify stable leaves expand in production-root order for reordered cascades
def test_family_reordered_decays():
    family = load_module("mg5_family")
    raw_source = """
// Process: g d > d z QCD<=1 QED<=1 @1
// *   Decay: z > mu+ mu- WEIGHTED<=2
"""
    assert channel_pairs(family.channels(raw_source)) == (((21, 1), (1, -13, 13)),)


# Verify repeated decay mothers expand occurrence by occurrence in DFS order
def test_family_repeated_nested_decays():
    family = load_module("mg5_family")
    raw_source = """
// Process: g g > h g QCD<=1 QED<=1 @1
// *   Decay: h > z z WEIGHTED<=2
// *   Decay: z > e+ e- WEIGHTED<=2
// *   Decay: z > mu+ mu- WEIGHTED<=2
"""
    assert channel_pairs(family.channels(raw_source)) == (((21, 21), (-11, 11, -13, 13, 21)),)


# Verify unrelated generated comments do not split one process decay block
def test_decay_blocks_with_comments():
    family = load_module("mg5_family")
    raw_source = """
// Process: g d > z d QCD<=1 QED<=1 @1
// Additional generated process channel_data
// *   Decay: z > mu+ mu- WEIGHTED<=2
"""
    assert channel_pairs(family.channels(raw_source)) == (((21, 1), (-13, 13, 1)),)


# Verify the generated particle map covers SM massive and fermion states
def test_family_channels_cover_sm_particles():
    family = load_module("mg5_family")
    raw_source = """
// Process: t t~ > w+ w- QCD<=2 QED<=2 @1
// *   Decay: w+ > ta+ vt WEIGHTED<=2
// *   Decay: w- > ta- vt~ WEIGHTED<=2
// Process: e+ e- > h z QED<=2 @2
// *   Decay: z > ve ve~ WEIGHTED<=2
"""
    assert channel_pairs(family.channels(raw_source)) == (
        ((6, -6), (-15, 16, 15, -16)),
        ((-11, 11), (25, 12, -12)),
    )


# Verify one model supplied particle map resolves BSM generated tokens
def test_family_channels_cover_model_particle_pdgs():
    family = load_module("mg5_family")
    raw_source = "// Process: x x~ > y y~ QED=0 @1\n"
    particle_pdgs = {
        "x": 9000001,
        "x~": -9000001,
        "y": 9000002,
        "y~": -9000002,
    }
    assert channel_pairs(family.channels(raw_source, particle_pdgs)) == (
        ((9000001, -9000001), (9000002, -9000002)),
    )


# Verify equal stable leaves retain distinct exact resonance topologies
def test_equal_leaf_resonances():
    family = load_module("mg5_family")
    raw_source = """
// Process: g g > z QED=2 @1
// *   Decay: z > mu+ mu- WEIGHTED<=2
// Process: g g > h QED=2 @2
// *   Decay: h > mu+ mu- WEIGHTED<=2
"""
    channels = family.channels(raw_source)
    assert channel_pairs(channels) == (
        ((21, 21), (-13, 13)),
        ((21, 21), (-13, 13)),
    )
    assert channels[0].topology != channels[1].topology
    assert channels[0].topology[0].pdg == 23
    assert channels[1].topology[0].pdg == 25
    family.validate_channel_structure([(channels[0],), (channels[1],)])
    with pytest.raises(RuntimeError, match="Duplicate exact generated subprocess channel"):
        family.validate_channel_structure([(channels[0],), (channels[0],)])


# Verify stale decay comments cannot disagree with generated external counts
def test_final_count_mismatch():
    family = load_module("mg5_family")
    layout = load_module("output_layout")
    raw_header = """
class CPPProcess {
  static const int ninitial = 2;
  static const int nexternal = 5;
};
"""
    raw_source = "// Process: u u~ > mu+ mu- QED<=2 @1\n"
    with pytest.raises(RuntimeError, match="Stable final count 2.*external count 3"):
        family.transform_subprocess(
            raw_header,
            raw_source,
            "MG5_TEST",
            "P1",
            "Parameters_sm.h",
            "HelAmps_sm.h",
            "Parameters_sm",
            "sm",
            False,
            layout.family_cpp_directory("parton", "MG5_TEST"),
        )


# Verify the known two-flow Compton channel retains MG matrix_elements JAMP ordering
def test_pp_jj_compton_flow_order():
    regenerate = load_module("regenerate")
    family_manifest, model = checked_in_family_manifest(regenerate, "MG5_PP_JJ")
    channel_data = regenerate.load_family_channels(family_manifest, model)
    subprocess = next(
        row
        for row in channel_data.subprocesses
        if any(channel.initial == (21, 2) and channel.final == (21, 2) for channel in row.channels)
    )
    canonical = next(channel for channel in subprocess.channels if channel.initial == (21, 2))
    mirrored = next(channel for channel in subprocess.channels if channel.initial == (2, 21))

    assert canonical.external_color_representations == (8, 3, 8, 3)
    assert canonical.external_color_flows == (
        ((1, 2), (3, 0), (3, 2), (1, 0)),
        ((3, 2), (2, 0), (3, 1), (1, 0)),
    )
    assert mirrored.external_color_representations == (3, 8, 8, 3)
    assert mirrored.external_color_flows == (
        ((3, 0), (1, 2), (3, 2), (1, 0)),
        ((2, 0), (3, 2), (3, 1), (1, 0)),
    )


# Verify persistent channels reject color slots incompatible with signed representations
def test_family_channels_malformed_color_slots():
    family = load_module("mg5_family")
    regenerate = load_module("regenerate")
    family_manifest, model = checked_in_family_manifest(regenerate, "MG5_PP_JJ")
    channel_data = regenerate.load_family_channels(family_manifest, model)
    malformed = json.loads(json.dumps(family.family_channels_data(channel_data)))
    channel = next(
        channel
        for subprocess in malformed["subprocesses"]
        for channel in subprocess["channels"]
        if 8 in channel["external_color_representations"]
    )
    gluon = channel["external_color_representations"].index(8)
    flow = channel["external_color_flows"][0]
    flow[2 * gluon + 1] = flow[2 * gluon]

    with pytest.raises(RuntimeError, match="octet leg has invalid"):
        family.family_channels_from_data(malformed)


# Verify every family generation_setup input is owned by the persistent sidecar
@pytest.mark.parametrize(
    "mutation",
    (
        "model",
        "model_import",
        "complex_mass_scheme",
        "definitions",
        "processes",
        "particle_pdgs",
        "alpha_qed",
        "mass_overrides",
    ),
)
def test_family_stale_setup(mutation):
    regenerate = load_module("regenerate")
    original_family, original_model = checked_in_family_manifest(regenerate, "MG5_PP_ZJ")
    family_manifest = json.loads(json.dumps(original_family))
    model = json.loads(json.dumps(original_model))

    if mutation == "model":
        family_manifest["model"] = "alternate_sm"
    elif mutation == "model_import":
        model["import"] = "sm-no_b_mass"
    elif mutation == "complex_mass_scheme":
        model["complex_mass_scheme"] = True
    elif mutation == "definitions":
        family_manifest["definitions"][0] = "define p = u d s c b g u~ d~ s~ c~ b~"
    elif mutation == "processes":
        family_manifest["processes"][0] += " QCD=0"
    elif mutation == "particle_pdgs":
        model["particle_pdgs"] = {"x": 9000001}
    elif mutation == "alpha_qed":
        model["alpha_qed"]["inverse_alpha_zero"] += 1.0
    elif mutation == "mass_overrides":
        family_manifest["mass_overrides"]["5"] = 1.0
    with pytest.raises(RuntimeError, match="generation setup"):
        regenerate.load_family_channels(family_manifest, model)


# Verify the source digest is checked against installed family sources
def test_family_channels_rejects_stale_source_digest():
    family = load_module("mg5_family")
    regenerate = load_module("regenerate")
    root = Path(__file__).resolve().parents[3]
    family_manifest, model = checked_in_family_manifest(regenerate, "MG5_PP_Z")
    channel_data = regenerate.load_family_channels(family_manifest, model)
    malformed = json.loads(json.dumps(family.family_channels_data(channel_data)))
    malformed["mg5_source"]["source_digest"] = "0" * 64
    stale = family.family_channels_from_data(malformed)

    with pytest.raises(RuntimeError, match="Stale MG5 source"):
        regenerate.validate_mg5_source(family_manifest, stale, root)


# Verify installed source and header bytes both contribute to the digest
@pytest.mark.parametrize(
    ("source", "filename"),
    (
        (False, "Test.h"),
        (True, "Test.cc"),
    ),
)
def test_family_source_fingerprint(tmp_path, source, filename):
    regenerate = load_module("regenerate")
    layout = load_module("output_layout")
    family = {"name": "MG5_TEST", "projection": "parton"}
    directory = layout.family_cpp_directory("parton", "MG5_TEST")
    header = tmp_path / layout.header_path(directory, "Test.h")
    cpp_source = tmp_path / layout.cpp_source_path(directory, "Test.cc")
    header.parent.mkdir(parents=True)
    cpp_source.parent.mkdir(parents=True)
    header.write_text("header\n")
    cpp_source.write_text("source\n")
    before = regenerate.family_installed_source_digest(family, tmp_path)

    target = (
        tmp_path / layout.cpp_source_path(directory, filename)
        if source
        else tmp_path / layout.header_path(directory, filename)
    )
    target.write_text(target.read_text() + "mutation\n")

    assert regenerate.family_installed_source_digest(family, tmp_path) != before


# Verify namespace qualification preserves multiline C++ comments
def test_std_qualification_block_comments():
    module = load_module("cpp_support")
    source = """/*
 * A real vector and complex coefficient remain prose
 */
vector<complex<double>> values;
"""
    converted = module.qualify_std_text(source, {"complex", "real", "vector"})
    assert "A real vector and complex coefficient remain prose" in converted
    assert "std::real" not in converted
    assert "std::vector<std::complex<double>> values;" in converted


# Verify generic function extraction ignores braces in comments and literals
def test_cpp_function_extraction_lexical_braces():
    support = load_module("cpp_support")
    source = """// void Model::couplings() { fake(); }
const char *description = "void Model::couplings() { fake(); }";
void Model::couplings() {
  const char *message = "not a closing brace: }";
  // Neither is this }
  /* Or this opening brace { */
  if (message[0]) { use(message); }
}
void Model::next() {}
"""

    start, end, block = support.function_block(source, "void Model::couplings()")
    assert start == source.rindex("void Model::couplings()")
    assert source[start:end] == block
    assert block.endswith("\n}")
    assert "void Model::next()" not in block


# Verify non-SM families can omit the optional alpha(0) adapter
@pytest.mark.parametrize("trailing_space", ["", " ", "  \t"])
def test_family_alpha_adapter(trailing_space):
    family = load_module("mg5_family")
    layout = load_module("output_layout")
    raw_source = """
#include "CPPProcess.h"
#include "HelAmps_bsm.h"
using namespace MG5_bsm;
//==========================================================================
// Class member functions
void CPPProcess::initProc(std::string param_card_name)
{
  pars = Parameters_bsm::getInstance();
  SLHAReader slha(param_card_name);
  pars->setIndependentParameters(slha);
}
void CPPProcess::sigmaKin()
{
  pars->setDependentParameters();
  pars->setDependentCouplings();
}
"""
    raw_source = raw_source.replace("SLHAReader slha(param_card_name);", f"SLHAReader slha(param_card_name);{trailing_space}")
    converted = family.transform_subprocess_source(
        raw_source,
        "MG5_BSM",
        "MG5_BSM_P1",
        "HelAmps_bsm.h",
        "Parameters_bsm",
        "bsm",
        alpha_zero=False,
        include_directory=layout.family_cpp_directory("parton", "MG5_BSM"),
    )
    assert "setDependentParameters(alphaS)" in converted
    assert "setAlphaQEDZero" not in converted
    assert "namespace MG5_BSM" in converted
    assert "SLHAReader slha(param_card_name)" not in converted
    assert "InitParameters(SLHAReader slha)" in converted


# Verify checked family imports retain the MadGraph final-state denominator
@pytest.mark.parametrize(
    ("family_name", "filename", "denominator", "final_symmetry", "initial_denominator"),
    (
        (
            "MG5_PP_Z",
            "MG5_PP_Z_P1_Sigma_sm_lepton_masses_uux_epem.cc",
            36,
            1,
            36,
        ),
        (
            "MG5_PP_ZJ",
            "MG5_PP_ZJ_P1_Sigma_sm_lepton_masses_gu_epemu.cc",
            96,
            1,
            96,
        ),
        (
            "MG5_PP_JJ",
            "MG5_PP_JJ_P1_Sigma_sm_lepton_masses_uux_bbx.cc",
            36,
            1,
            36,
        ),
        (
            "MG5_PP_JJ",
            "MG5_PP_JJ_P1_Sigma_sm_lepton_masses_uux_gg.cc",
            72,
            2,
            36,
        ),
    ),
)
def test_checked_family_denominator_split(
    family_name, filename, denominator, final_symmetry, initial_denominator
):
    regenerate = load_module("regenerate")
    layout = load_module("output_layout")
    root = Path(__file__).resolve().parents[3]
    family, _model = checked_in_family_manifest(regenerate, family_name)
    source = checked_in_family_path(root, layout, family, filename, source=True).read_text()
    arrays = re.findall(r"const int denominators\[nprocesses\] = \{([^}]*)\};", source)

    assert arrays
    for values in arrays:
        assert {int(value.strip()) for value in values.split(",")} == {denominator}
    assert denominator == final_symmetry * initial_denominator


# Build a synthetic grouped MG5 subprocess with selected leg permutations
def synthetic_grouped_subprocess(permutations, matrix_functions=None):
    class_name = "MG5_TEST_P1"
    nprocesses = len(permutations)
    nexternal = len(permutations[0])
    if matrix_functions is None:
        matrix_functions = tuple(f"matrix_{index}" for index in range(nprocesses))
    header = f"""
class {class_name} {{
  static const int ninitial = 2;
  static const int nexternal = {nexternal};
  static const int nprocesses = {nprocesses};
}};
"""
    evaluations = []
    for index, (permutation, matrix_function) in enumerate(
        zip(permutations, matrix_functions, strict=True)
    ):
        evaluations.extend(f"  perm[{leg}] = {value};" for leg, value in enumerate(permutation))
        evaluations.append("  calculate_wavefunctions(perm, helicities[0]);")
        evaluations.extend(f"  perm[{leg}] = {leg};" for leg in range(nexternal))
        evaluations.append(f"  t[{index}] = {matrix_function}();")
    sigma_hat = [
        f"  if (id1 == {index}) {{ return matrix_element[{index}]; }}"
        for index in range(nprocesses)
    ]
    unique_functions = tuple(dict.fromkeys(matrix_functions))
    matrix_blocks = []
    for index, matrix_function in enumerate(unique_functions):
        matrix_blocks.append(
            f"""
double {class_name}::{matrix_function}()
{{
  const int ncolor = 1;
  std::complex<double> jamp[ncolor];
  static const double denom[ncolor] = {{{index + 1}}};
  static const double cf[ncolor][ncolor] = {{{{{index + 2}}}}};
  // Calculate color flows
  jamp[0] = amp[{index}];
  // Sum and square the color flows to get the matrix element
  return 0.0;
}}
"""
        )
    denominators = ", ".join(str(4 * (index + 1)) for index in range(nprocesses))
    helicities = ", ".join("-1" if index % 2 == 0 else "1" for index in range(nexternal))
    source = f"""
void {class_name}::sigmaKin()
{{
  const int ncomb = 1;
  const int helicities[ncomb][nexternal] = {{{{{helicities}}}}};
  const int denominators[nprocesses] = {{{denominators}}};
  double t[nprocesses];
  int perm[nexternal];
  for (int leg = 0; leg < nexternal; ++leg) {{ perm[leg] = leg; }}
{chr(10).join(evaluations)}
}}

double {class_name}::sigmaHat()
{{
{chr(10).join(sigma_hat)}
  return 0.;
}}
{"".join(matrix_blocks)}
"""
    return class_name, header, source


# Verify arbitrary grouped subprocesses preserve complete external-leg permutations
def test_subprocess_color_permutations():
    family = load_module("mg5_family")
    permutations = (
        (0, 1, 2, 3, 4),
        (0, 1, 3, 4, 2),
        (1, 0, 4, 2, 3),
    )
    class_name, header, source = synthetic_grouped_subprocess(permutations)

    evaluations = family.process_evaluations(source, header, class_name)
    assert tuple(row.permutation for row in evaluations) == permutations
    assert tuple(row.matrix_function for row in evaluations) == (
        "matrix_0",
        "matrix_1",
        "matrix_2",
    )
    assert not family.legacy_evaluation_structure(evaluations)

    helicity = family.helicity_definition(source, header, class_name, evaluations=evaluations)
    assert (
        "const int permutations[nprocesses][nexternal] = "
        "{{0, 1, 2, 3, 4}, {0, 1, 3, 4, 2}, {1, 0, 4, 2, 3}};"
    ) in helicity
    assert "outgoing[physical_leg - ninitial] = helicities[ihel][leg];" in helicity
    assert "selected >= nprocesses" in helicity

    color = family.color_definition(source, class_name, evaluations)
    leading = family.leading_color_definition(source, class_name, evaluations)
    for index in range(3):
        assert f"case {index}:" in color
        assert f"jamp[0] = amp[{index}];" in color
        assert f"case {index}:" in leading


# Verify generated family decoding ignores comment and literal lookalikes
def test_subprocess_cpp_parsing_lexical():
    family = load_module("mg5_family")
    permutations = ((0, 1, 2, 3, 4), (1, 0, 2, 3, 4))
    class_name, header, source = synthetic_grouped_subprocess(permutations)
    source = source.replace(
        f"void {class_name}::sigmaKin()\n{{",
        f"""void {class_name}::sigmaKin()
{{
  const char *fake = "t[99] = matrix_fake(); }}";
  // t[98] = matrix_fake();
  /* perm[0] = 99; calculate_wavefunctions(perm, helicities[0]); */""",
        1,
    )
    source = source.replace(
        f"double {class_name}::sigmaHat()\n{{",
        f"""double {class_name}::sigmaHat()
{{
  const char *fake = "matrix_element[99] }}";
  // return matrix_element[98];
  /* return matrix_element[97]; */""",
        1,
    )

    evaluations = family.process_evaluations(source, header, class_name)
    assert tuple(row.permutation for row in evaluations) == permutations
    assert tuple(row.index for row in evaluations) == (0, 1)


# Verify a two-process final-state permutation does not require mirror structure
def test_subprocess_nonmirror_permutation():
    family = load_module("mg5_family")
    permutations = ((0, 1, 2, 3, 4), (0, 1, 3, 2, 4))
    class_name, header, source = synthetic_grouped_subprocess(permutations)

    evaluations = family.process_evaluations(source, header, class_name)
    definition = family.helicity_definition(source, header, class_name, evaluations=evaluations)

    assert tuple(row.permutation for row in evaluations) == permutations
    assert not family.legacy_evaluation_structure(evaluations)
    assert "const int permutations[nprocesses][nexternal]" in definition
    assert "std::swap(perm[0], perm[1])" not in definition


# Compute one malformed grouped source and its expected decoder diagnostic
def malformed_grouped_source(source, mutation):
    if mutation == "duplicate":
        return source.replace("t[2] = matrix_2();", "t[1] = matrix_2();"), "Duplicate"
    if mutation == "out_of_range":
        return source.replace("t[2] = matrix_2();", "t[3] = matrix_2();"), "Out-of-range"
    if mutation == "missing":
        return source.replace("  t[2] = matrix_2();\n", ""), "Missing sigmaKin"
    if mutation == "invalid_permutation":
        needle = "  perm[4] = 3;\n  calculate_wavefunctions"
        return source.replace(
            needle, "  perm[4] = 2;\n  calculate_wavefunctions"
        ), "Invalid generated"
    if mutation == "selected_out_of_range":
        return source.replace(
            "return matrix_element[2]", "return matrix_element[3]"
        ), "Out-of-range"
    if mutation == "selected_missing":
        return source.replace(
            "return matrix_element[2]", "return matrix_element[1]"
        ), "Missing sigmaHat"
    return (
        source.replace("t[2] = matrix_2();", "t[2] = matrix_2() + matrix_0();"),
        "Unsupported sigmaKin",
    )


# Verify malformed generated indices and permutations fail closed
@pytest.mark.parametrize(
    "mutation",
    (
        "duplicate",
        "out_of_range",
        "missing",
        "invalid_permutation",
        "selected_out_of_range",
        "selected_missing",
        "matrix_expression",
    ),
)
def test_subprocess_malformed_evaluation_structure(mutation):
    family = load_module("mg5_family")
    permutations = (
        (0, 1, 2, 3, 4),
        (0, 1, 3, 4, 2),
        (1, 0, 4, 2, 3),
    )
    class_name, header, source = synthetic_grouped_subprocess(permutations)
    malformed, message = malformed_grouped_source(source, mutation)

    with pytest.raises(RuntimeError, match=message):
        family.process_evaluations(malformed, header, class_name)


# Verify existing incoming-mirror subprocesses retain the compact generated path
def test_subprocess_existing_mirror_pair_path():
    family = load_module("mg5_family")
    regenerate = load_module("regenerate")
    layout = load_module("output_layout")
    root = Path(__file__).resolve().parents[3]
    class_name = "MG5_PP_ZJ_P1_Sigma_sm_lepton_masses_gu_epemu"
    family_manifest, _model = checked_in_family_manifest(regenerate, "MG5_PP_ZJ")
    source = checked_in_family_path(
        root, layout, family_manifest, f"{class_name}.cc", source=True
    ).read_text()
    header = checked_in_family_path(root, layout, family_manifest, f"{class_name}.h").read_text()

    evaluations = family.process_evaluations(source, header, class_name)
    definition = family.helicity_definition(source, header, class_name, evaluations=evaluations)

    assert evaluations[1].permutation == (1, 0, 2, 3, 4)
    assert family.legacy_evaluation_structure(evaluations)
    assert "if (selected == 1) { std::swap(perm[0], perm[1]); }" in definition
    assert "const int permutations[nprocesses][nexternal]" not in definition


# Generate pole metadata for arbitrary UFO names and reject unavailable parameters
def test_model_particle_params_follow_ufo_symbols():
    support = load_module("mg5_support")
    header = "#include <complex>\nclass Parameters_X { public: double ZERO, mdl_muX, mdl_gammaX; };"
    particles = [{"pdg": 900001, "mass": "mdl_muX", "width": "mdl_gammaX"},
                 {"pdg": 22, "mass": "ZERO", "width": "ZERO"}]
    source = "void Parameters_X::setIndependentParameters(SLHAReader &slha) { ZERO=0; mdl_muX=1; mdl_gammaX=2; }"
    result = support.add_model_particles(header, particles, source)
    assert "{900001, {mdl_muX, mdl_gammaX}}" in result
    assert "{22, {ZERO, ZERO}}" in result
    with pytest.raises(RuntimeError, match="Missing generated pole parameter"):
        support.add_model_particles(header, [{"pdg": 900002, "mass": "missing", "width": "ZERO"}], source)


# Derive coupling powers from real diagrams for bounds, exact orders and interference
@pytest.mark.parametrize("process, orders", [
    ("a a > e+ e- QED=4 QCD=3", {(0, 2)}),
    ("a a > e+ e- QED==2 QCD==0", {(0, 2)}),
    ("u u~ > u u~ QED=2 QCD=2", {(2, 0), (0, 2)}),
])
def test_real_mg5_amplitude_orders(tmp_path, mg5_root, process, orders):
    family = load_module("mg5_family")
    result = family.generate_family_color_structure(mg5_root, tmp_path / "orders", "sm", [], [process])
    actual = {(dict(row).get("QCD", 0), dict(row).get("QED", 0)) for item in result for row in item.orders}
    assert actual == orders


# Discover MSSM particle names and signed Majorana masses from the real UFO
# instead of an SM token table or manually supplied PDG map
def test_real_mg5_bsm_particle_metadata(mg5_root):
    regenerate = load_module("regenerate")
    model = {"import": "MSSM_SLHA2"}
    particles = regenerate.load_model_particles(mg5_root, model)
    neutralino = next(p for p in particles if p["pdg"] == 1000022)
    assert neutralino["signed_mass"]
    assert model["particle_pdgs"]["n1"] == 1000022
    assert model["particle_pdgs"]["x1+"] == 1000024
    assert model["particle_pdgs"]["x1-"] == -1000024


# Preserve MG5 sextet LHE signs and exact finite-Nc normalization
# using the real color algebra supplied by MadGraph
def test_real_mg5_sextet_color_projection(mg5_root):
    color = load_module("mg5_color")
    _, color_amp, algebra = color.load_madgraph(mg5_root)
    factor = algebra.ColorString([algebra.T6(1, 2)])
    basis = color_amp.ColorBasis()
    basis[factor.to_immutable()] = []
    flow = basis.color_flow_decomposition({1: 6, 2: -6}, 0)[0]
    assert flow[1][0] > 0 and flow[1][1] < 0
    assert flow[2][0] < 0 and flow[2][1] > 0
    family = load_module("mg5_family")
    legs = ((0, 0), (0, 0), *(tuple((1 if tag >= 0 else -1) * (abs(tag) % 500) for tag in flow[i]) for i in (1, 2)))
    channel = family.Channel((22, 22), (6000001, -6000001), (), (1, 1, 6, -6), (legs,))
    family.validate_external_color_structure(channel)


# Evaluate a non-SMINPUTS electromagnetic input through the actual UFO reader
def test_real_mg5_alternative_input_blocks(tmp_path, mg5_root):
    family = load_module("mg5_family")
    color = load_module("mg5_color")
    with family.chdir(tmp_path):
        command_class, _ = family.load_madgraph_family_api(mg5_root)
        command = command_class()
        command.no_notification()
        command.exec_cmd("import model sm-lepton_masses", printcmd=False)
        model = command._curr_model
        root = Path(__file__).resolve().parents[3]
        card = (root / "MG5cards/Photon/yy_ll/param_card.dat").read_text()
        expected = color.model_couplings(model, card, "mdl_ee")
        for parameter in model.get("parameters")[("external",)]:
            if parameter.lhablock.lower() == "sminputs":
                parameter.lhablock = "NEWINPUTS"
        card = re.sub(r"(?i)block\s+sminputs", "BLOCK NEWINPUTS", card)
        assert color.model_couplings(model, card, "mdl_ee") == pytest.approx(expected)


# Compare converted MSSM complex couplings with the UFO interpreter and retain
# the signed neutralino mass while exposing its positive pole to phase space
def test_real_mg5_mssm_couplings(tmp_path, mg5_root):
    import io
    import math
    import subprocess

    family = load_module("mg5_family")
    support = load_module("mg5_support")
    regenerate = load_module("regenerate")
    coupling = load_module("mg5_couplings")
    root = Path(__file__).resolve().parents[3]
    export = tmp_path / "mssm"
    with family.chdir(tmp_path):
        command_class, _ = family.load_madgraph_family_api(mg5_root)
        command = command_class()
        command.no_notification()
        command.exec_cmd("set nb_core 4", printcmd=False)
        command.exec_cmd("import model MSSM_SLHA2", printcmd=False)
        command.exec_cmd("generate a a > x1+ x1- h01", printcmd=False)
        command.exec_cmd(f"output standalone_cpp {export}", printcmd=False)
        model = command._curr_model
        from models.check_param_card import ParamCard
        from models.model_reader import ModelReader

        charge = next(p for group in model.get("parameters").values() for p in group if p.name == "mdl_ee")
        charge.expr = repr(math.sqrt(4.0 * math.pi / 137.03599908))
        reader = ModelReader(model)
        reader.set_parameters_and_couplings(ParamCard(io.StringIO((export / "Cards/param_card.dat").read_text())))
        expected = reader.get("coupling_dict")
    particles = regenerate.load_model_particles(mg5_root, {"import": "MSSM_SLHA2"})
    name = "Parameters_MSSM_SLHA2"
    raw_source = (export / f"src/{name}.cc").read_text()
    header = support.transform_parameters_header((export / f"src/{name}.h").read_text(), name, True)
    header = support.add_model_particles(header, particles, raw_source, "mdl_ee")
    include = tmp_path / "include/Graniitti/Amplitude/MG5/Runtime/Models/mssm"
    include.mkdir(parents=True)
    (include / f"{name}.h").write_text(header)
    source = tmp_path / "parameters.cc"
    source.write_text(support.transform_parameters_source(raw_source, name, f"{name}.h", "mdl_ee", None,
                                                          137.03599908, "Runtime/Models/mssm"))
    couplings = [target for method in ("setIndependentCouplings", "setDependentCouplings")
                 for target, _ in coupling.assignments(raw_source, name, method)]
    output = "\n".join(f'std::cout << "{key} " << p.{key}.real() << " " << p.{key}.imag() << "\\n";' for key in couplings)
    neutralino = next(p for p in particles if p["pdg"] == 1000022)
    probe = tmp_path / "couplings.cc"
    probe.write_text(f'''#include "Graniitti/Amplitude/MG5/Runtime/Models/mssm/{name}.h"
#include <cassert>
#include <iomanip>
#include <iostream>
int main(int argc, char **argv) {{
  SLHAReader card(argv[1]);
  {name} p;
  p.setIndependentParameters(card);
  p.setDependentParameters(card.get_block_entry("sminputs", 3));
  p.setIndependentCouplings();
  p.setDependentCouplings();
  p.setAlphaQEDZero();
  std::cout << std::setprecision(17);
  {output}
  const double mass = p.Particles().at(1000022).mass;
  card.set_block_entry("mass", 1000022, -mass);
  p.setIndependentParameters(card);
  gra::mg5::ValidateModel(card, p.Particles());
  assert(p.{neutralino['mass']} < 0.0 && p.Particles().at(1000022).mass > 0.0);
}}
''')
    binary = tmp_path / "couplings"
    subprocess.run([os.environ.get("CXX", "c++"), "-std=c++20", "-I" + str(tmp_path / "include"),
                    "-I" + str(root / "include"), str(probe), str(source),
                    str(root / "src/Amplitude/MG5/Runtime/read_slha.cc"), "-o", str(binary)], check=True)
    result = subprocess.run([str(binary), str(export / "Cards/param_card.dat")], check=True, text=True, capture_output=True)
    for line in result.stdout.splitlines():
        key, real, imaginary = line.split()
        assert complex(float(real), float(imaginary)) == pytest.approx(expected[key], rel=2e-12, abs=1e-14)


# Use actual loop diagram orders even when the MG5 bounds are higher
def test_real_mg5_loop_orders(tmp_path, mg5_root):
    family = load_module("mg5_family")
    madloop = load_module("madloop")
    output = tmp_path / "loop"
    entry = {"name": "gg_aa", "model": "loop_sm", "process": "g g > a a QCD=4 QED=4 [noborn=QCD]"}
    with family.chdir(tmp_path):
        command_class, _ = family.load_madgraph_family_api(mg5_root)
        command = command_class()
        command.no_notification()
        for setting in ("ninja None", "collier None", "automatic_html_opening False", "nb_core 4"):
            command.exec_cmd(f"set {setting}", printcmd=False)
        command.exec_cmd("import model loop_sm", printcmd=False)
        command.exec_cmd(f"generate {entry['process']}", printcmd=False)
        command.exec_cmd(f"output {output}", printcmd=False)
    model = madloop.loop_model(mg5_root, output, entry, {"import": "loop_sm", "alpha_qed": {"charge": "mdl_ee"}})
    metadata = madloop.inspect_output(output, entry, model)
    assert metadata.qcd_order == metadata.qed_order == 2
    assert metadata.alpha_zero
    assert metadata.color_norm == pytest.approx(2.0)
    assert metadata.helicity_average == 4
    assert metadata.nexternal == 4
